services:
  - type: web
    name: eraya-ops-hub
    env: python
    plan: free  # or starter, standard, etc.
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.factory:create_app --factory --host 0.0.0.0 --port $PORT
    autoDeploy: true
